<Project Sdk="Tomat.Terraria.ModLoader.Sdk">
	
	<!-- Daybreak -->
	<ItemGroup>
		<Analyzer Include="libanalyzer\Daybreak.CodeAnalysis.dll" />
	</ItemGroup>

	<!-- SubworldLibrary -->
	<ItemGroup>
		<ProjectReference Include="..\subworld-library\src\SubworldLibrary\SubworldLibrary.csproj"/>
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<TmlVersion>dev</TmlVersion>
	</PropertyGroup>

	<!-- Publicizer -->
	<ItemGroup>
		<Publicize Include="FNA;ReLogic;MonoMod.RuntimeDetour" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
	</ItemGroup>

	<PropertyGroup>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

		<Nullable>enable</Nullable>

		<!-- Type conflict with 'IgnoresAccessChecksToAttribute' -->
		<NoWarn>$(NoWarn);CS0436</NoWarn>
	</PropertyGroup>

</Project>